### ISSUE TITLE
你好，这对布局要求是一定要是列表形式的，请问能完善下么？

### ISSUE THREAD

**Issue by xiangjiejie** [huxiaoqi567/xscroll#14]
终于找到这套路，只能 在列表形式的dom内有滚动效果，不是列表的不能再继续滚动。未看源码，不知产生这个问题的原因是什么，像iscroll即使不是列表形式的，会有卡顿但至少使用上还是正常的

**Comment by huxiaoqi567** [comment]
@xiangjiejie   xscroll本身的定位和iscroll是一样的，他就是浏览器overflow的polyfill，只要满足能够滚动的条件，是和内容无关的。至于你说的列表是因为xscroll支持的infinite插件，它的实现基于ListView的实现，通过dom的重复利用来提高超长列表的性能 http://xscroll.github.io/demos/scroll-2d.html 任意内容的水平+垂直滚动demo
