### ISSUE TITLE
如何支持嵌套滑动

### ISSUE THREAD

**Issue by guhongjie** [huxiaoqi567/xscroll#15]
如何支持嵌套滑动

**Comment by cjlice** [comment]
百度一下jroll，这个插件支持
看demo，暂时不支持PC，可以在谷歌模拟器打开： http://www.chjtx.com/JRoll/demos/

**Comment by huxiaoqi567** [comment]
@guhongjie  嵌套滚动冒泡的处理  可以使用父级superScroll.controller.add(subScroll);的方式
