### ISSUE TITLE
在VUE里面import或者require报错

### ISSUE THREAD

**Issue by zigary** [huxiaoqi567/xscroll#23]
在vue里面使用，XScroll = require('xscroll');报错

**Comment by huxiaoqi567** [comment]
应该是package.json的main入口文件指向问题，已经修复了

**Comment by zigary** [comment]
还是一样的报错，请检测完整才close

 error  in ./~/xscroll/src/xscroll.js

Module parse failed: F:\WebstormProjects\dicos_vue\node_modules\xscroll\src\xscroll.js 'return' outside of function (55:1)
You may need an appropriate loader to handle this file type.
| /** ignored by jsdoc **/
| else {
|       return window.XScroll = XScroll;
| }

**Comment by qqcome110** [comment]
遇到同样的错
