### ISSUE TITLE
vux scroller拖拽又回到顶部

### ISSUE THREAD

**Issue by AliKhan1990** [huxiaoqi567/xscroll#25]
1. 使用vux组件scroller，纵向拖拽窗体整体回弹到顶部，通过浏览器检查看到transform: translate自动变为0。
2. 代码：

```
<scroller class="goods-wrap" lock-x >
    ...
</scroll>
```

**Comment by airyland** [comment]
1.既然是 VUX 组件就先到 VUX 提 issue
2.你这样的代码对解决问题没有帮助，script 部分呢，数据是不是异步，有没有 reset？

**Comment by AliKhan1990** [comment]
嗯嗯，实在抱歉，新手很多东西不懂，多多包涵，感谢您的耐心回复。
问题解决了，是:bounce属性的原因。
