### ISSUE TITLE
不兼容新版的hammer?

### ISSUE THREAD

**Issue by hzh1990** [huxiaoqi567/xscroll#7]
xscroll  version: 3.1.2
hammer version: 2.0.7
问题: 滚动会弹回

**Comment by hzh1990** [comment]
@huxiaoqi567

**Comment by huxiaoqi567** [comment]
目前xscroll用的 2.0.4 的hammer  https://github.com/huxiaoqi567/xscroll/blob/master/src/hammer.js 能把你的问题说具体么？ 滚动会弹回是不是你的容器边界不正确。 确认下xscroll.containerHeight和xscroll.height的关系

**Comment by hzh1990** [comment]
demo: 
scroll-y: http://output.jsbin.com/buquwakali  
scroll-x: http://output.jsbin.com/vuyomiwuyo/1

hammer: 2.0.7
