### ISSUE TITLE
这个库很赞，请教个问题

### ISSUE THREAD

**Issue by warmhug** [huxiaoqi567/xscroll#9]
scroll 事件在老的机型上有问题，但在 ios8 和安卓4上触发的频率甚至比 touchmove 更多，也即没什么问题了。所以是否可以用原生的 scroll 事件来做滚动，而不需要再用 touch 事件模拟出滚动的效果来？（拖动、左划/右划这些还是可以基于类似 hammer.js 等手势库来做更方便一点）

**Comment by bammoo** [comment]
@warmhug 微信等很多 App 内 webview 还有问题的：http://developer.telerik.com/featured/scroll-event-change-ios-8-big-deal/，https://fe.ele.me/momentum-scrolling-on-ios/。

**Comment by warmhug** [comment]
链接错误、连起来了呀。看来不久后、大家都更新了内核，就能用scroll了。
